version: '2'
services:
  db:
    image: postgres
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: ./server
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./server:/usr/src/turfs
    ports:
      - 3000:3000 # 開発用
    depends_on:
      - db
volumes:
  mysql-data:
    driver: local
